version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB = wallet

  server:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgres://root:password@localhost:5432/wallet?sslmode=disable
