// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
	// negative values indicate deductions
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID               int64     `json:"id"`
	SenderWalletID   int64     `json:"sender_wallet_id"`
	ReceiverWalletID int64     `json:"receiver_wallet_id"`
	Amount           int64     `json:"amount"`
	CreatedAt        time.Time `json:"created_at"`
}

type User struct {
	ID                int64        `json:"id"`
	Username          string       `json:"username"`
	Email             string       `json:"email"`
	Firstname         string       `json:"firstname"`
	Lastname          string       `json:"lastname"`
	Password          string       `json:"password"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type Wallet struct {
	ID        int64     `json:"id"`
	Owner     int64     `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}
