// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Entry struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
	// negative values indicate deductions
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Funding struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	WalletID  int64     `json:"wallet_id"`
	Amount    int64     `json:"amount"`
	Success   bool      `json:"success"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	IpAddress    string    `json:"ip_address"`
	Location     string    `json:"location"`
	IsValid      bool      `json:"is_valid"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Transfer struct {
	ID               int64     `json:"id"`
	SenderWalletID   int64     `json:"sender_wallet_id"`
	ReceiverWalletID int64     `json:"receiver_wallet_id"`
	Amount           int64     `json:"amount"`
	CreatedAt        time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	Firstname         string    `json:"firstname"`
	Lastname          string    `json:"lastname"`
	Password          string    `json:"password"`
	IsVerified        bool      `json:"is_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type Wallet struct {
	ID        int64     `json:"id"`
	Owner     int64     `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}
